Improve look and feel
karakum-team/kotlin-mui-showcase pull request #6
Opened 2022-02-06 12:19 UTC by vie10

The content paper:

- Added minHeight for fill the visible space
- Added padding for beautify look and feel

Other:

- Added new size constant for padding

2022-02-06 12:20 UTC, vie10 commented on src/main/kotlin/team/karakum/common/Sizes.kt
> +        val Graceful = 30.px
Used in 2 places so is useful

2022-02-06 12:21 UTC, vie10 commented on src/main/kotlin/team/karakum/component/Content.kt
> +                    sx = jso {
Twice minus padding graceful because of the paper is padded by bottom and top

2022-02-06 12:25 UTC, vie10 commented
<img width="1440" alt="Screenshot 2022-02-06 at 14 24 23" src="https://user-images.githubusercontent.com/81972035/152680578-80a03c50-f127-4d00-b37b-dbdab4925bae.png">
Look and feel after improves. LGTM

2022-02-06 17:29 UTC, aerialist7 requested changes

2022-02-06 17:29 UTC, aerialist7 commented on src/main/kotlin/team/karakum/component/Content.kt
> +private val visibleHeight: Length
Think this calculations are redundant.

Now I've added Grid layout. 
Try to tune the grid to get `Content` component background to fill the entire grid cell

2022-02-06 17:36 UTC, aerialist7 commented
@vie10, also let me give a recommendation to you: please create a new branch in your repo and give it a PR-related name.
Then do your commits. And then send a PR.

This approach is more convenient and do not produce redundant commits like these
![image](https://user-images.githubusercontent.com/32072831/152693418-6375f16f-468e-4216-bec8-7818017cafa0.png)

2022-02-06 17:52 UTC, vie10 commented
> @vie10, also let me give a recommendation to you: please create a new branch in your repo and give it a PR-related name.
> 
> Then do your commits. And then send a PR.
> 
> 
> 
> This approach is more convenient and do not produce redundant commits like these
> 
> ![image](https://user-images.githubusercontent.com/32072831/152693418-6375f16f-468e-4216-bec8-7818017cafa0.png)
> 
> 

Thx, I'll

2022-02-07 17:39 UTC, aerialist7 commented on src/main/kotlin/team/karakum/common/Sizes.kt
> +        val Graceful = 30.px
Yep, but let's call it `Default`

2022-02-07 17:43 UTC, aerialist7 requested changes
Small refactoring required

2022-02-08 05:27 UTC, aerialist7 approved these changes

2022-02-08 05:28 UTC, merged